
---
title: "Материалы"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
---
# Методы анализа неоднородных данных и паттерн-анализ, 2025
 

### Обозначения
 
`r  shiny::icon("scroll")` -- презентация / конспект занятия / семинарский листочек
 
`r  shiny::icon("readme")` -- Reading
 
`r  shiny::icon("desktop")` -- материалы для практикума (данные, код)
 
`r  shiny::icon("pencil")` -- задание 
 
## Занятие 1
 
Тема: О чем курс и каковы правила игры? 
  
`r  shiny::icon("scroll")` <a href="MApolit_intro_2025.pdf" title=>Презентация-введение</a> 

`r  shiny::icon("scroll")` <a href="MApolit_lecture1_2025.pdf" title=>Лекция 1</a> 

Домашнее задание к 24 января (для тренировки, сдавать не нужно): 
 
`r  shiny::icon("pencil")` <a href="MApolit_hw1_2025.pdf" title=>Домашнее задание 1 </a> 

## Занятие 2
 
Тема: линейная регрессионная модель (введение)

`r  shiny::icon("scroll")` <a href="MApolit_lecture2_2025.pdf" title=>Лекция 2</a>

Домашнее задание к 31 января (для тренировки, сдавать не нужно): 
 
`r  shiny::icon("pencil")` <a href="MApolit_hw2_2025.pdf" title=>Домашнее задание 2 </a> 
 
`r  shiny::icon("pencil")` <a href="MApolit_hw2_solution.pdf" title=>Решение ДЗ 2 </a> 

## Занятие 3
 
Тема: линейная регрессионная модель (продолжение); модели с переменными взаимодействия

`r  shiny::icon("scroll")` <a href="MApolit_interactions.pdf" title=>Презентация: переменные взаимодействия</a>

Домашнее задание к 7 февраля: 
 
Обязательно: `r  shiny::icon("readme")` Brambor et al.

Дополнительно: `r  shiny::icon("readme")` Franzese, Kam, pp. 19 -- 39 

Домашнее задание к 9 февраля (бонусное, выполняется по желанию): 
 
`r  shiny::icon("pencil")` <a href="MApolit_hw3_bonus.pdf" title=>Домашнее задание 3 (бонусное) </a> 

## Занятие 4
 
Тема: регрессионные модели с переменными взаимодействия

`r  shiny::icon("scroll")` <a href="MApolit_seminar2.pdf" title=>Семинарский лист 2</a>

`r  shiny::icon("scroll")` <a href="MApolit_seminar2_solution.pdf" title=>Решение семинарского листка 2</a>

## Занятие 5 

Тема: введение в модели для анализа панельных данных

`r  shiny::icon("scroll")` <a href="FE--part-1-.html" title=>Конспект</a>

Домашнее задание: 
 
`r  shiny::icon("readme")`  <a href="https://disk.yandex.ru/i/G9DO5ZMwYmP2Mw" title=>Stock, Watson, Chapter 10 (10.1 - 10.3)</a>  

## Занятие 6

Тема: модели для анализа панельных данных (продолжение)

`r  shiny::icon("scroll")` <a href="MApolit_lecture_FE_RE.html" title=>Конспект</a>

Домашнее задание: 
 
`r  shiny::icon("readme")`  <a href="https://disk.yandex.ru/i/V6oQg2xZeysiDg" title=>Kropko, Kubinec, 2020</a>  
 
Вопросы к статье:
 
1) Приведите примеры содержательных вопросов, на которые могут помочь ответить модели с FE на пространственные единицы; с FE на временные периоды.
 
2) Как реализуется внутригрупповое преобразование в FE-моделях на пространственные единицы? А в случае если модель с FE на временные периоды? 
 
3) В чем отличие интерпретации оценок коэффициентов при предикторах в моделях с FE на пространственные единицы по сравнению с соответствующей интерпретацией в моделях с FE на временные периоды?  
 
4) Как устроена twoways FE-model? В чем ограничения такой модели? Почему ее нередко называют tricky model? 
